/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.conexion;

/**
 *
 * @author EMANUEL
 */
public class prueba extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEscritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSalir = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuPacientes = new javax.swing.JMenu();
        MenuRegistraP = new javax.swing.JMenuItem();
        MenuConsultaP = new javax.swing.JMenuItem();
        MenuMedico = new javax.swing.JMenu();
        MenuRegistrarM = new javax.swing.JMenuItem();
        MenuConsultarM = new javax.swing.JMenuItem();
        MenuEmpleado = new javax.swing.JMenu();
        MenuRegEmpleado = new javax.swing.JMenuItem();
        MenuConsultarEmpleado = new javax.swing.JMenuItem();
        MenuConsultorio = new javax.swing.JMenu();
        MenuRegistrarConsultorio = new javax.swing.JMenuItem();
        MenuConsultarConsultorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        PanelEscritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelEscritorioLayout = new javax.swing.GroupLayout(PanelEscritorio);
        PanelEscritorio.setLayout(PanelEscritorioLayout);
        PanelEscritorioLayout.setHorizontalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelEscritorioLayout.setVerticalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuSalir.setText("Archivo");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        MenuSalir.add(Salir);

        jMenuItem1.setText("Cambiar contraseña");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuSalir.add(jMenuItem1);

        jMenuBar1.add(MenuSalir);

        MenuPacientes.setText("Pacientes");

        MenuRegistraP.setText("Registrar Paciente");
        MenuRegistraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistraPActionPerformed(evt);
            }
        });
        MenuPacientes.add(MenuRegistraP);

        MenuConsultaP.setText("Consultar Paciente");
        MenuConsultaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaPActionPerformed(evt);
            }
        });
        MenuPacientes.add(MenuConsultaP);

        jMenuBar1.add(MenuPacientes);

        MenuMedico.setText("Medicos");

        MenuRegistrarM.setText("Registrar Medico");
        MenuRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarMActionPerformed(evt);
            }
        });
        MenuMedico.add(MenuRegistrarM);

        MenuConsultarM.setText("Consultar Medico");
        MenuMedico.add(MenuConsultarM);

        jMenuBar1.add(MenuMedico);

        MenuEmpleado.setText("Empleado");

        MenuRegEmpleado.setText("Registrar Empleado");
        MenuRegEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegEmpleadoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(MenuRegEmpleado);

        MenuConsultarEmpleado.setText("Consultar Empleado");
        MenuEmpleado.add(MenuConsultarEmpleado);

        jMenuBar1.add(MenuEmpleado);

        MenuConsultorio.setText("Consultorio");

        MenuRegistrarConsultorio.setText("Registrar Consultorio");
        MenuRegistrarConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarConsultorioActionPerformed(evt);
            }
        });
        MenuConsultorio.add(MenuRegistrarConsultorio);

        MenuConsultarConsultorio.setText("Consultar Consultorio");
        MenuConsultorio.add(MenuConsultarConsultorio);

        jMenuBar1.add(MenuConsultorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);  
    }//GEN-LAST:event_SalirActionPerformed

    private void MenuConsultaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultaPActionPerformed

    private void MenuRegistraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistraPActionPerformed
        
        FrmRegistro_Paciente VerFormulario = new FrmRegistro_Paciente ();
        PanelEscritorio.add(VerFormulario);
        VerFormulario.show();
        
        
    }//GEN-LAST:event_MenuRegistraPActionPerformed

    private void MenuRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarMActionPerformed
       
        FrmRegMedico VerFormulario = new FrmRegMedico();
        PanelEscritorio.add(VerFormulario);
        VerFormulario.show();
    }//GEN-LAST:event_MenuRegistrarMActionPerformed

    private void MenuRegEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegEmpleadoActionPerformed
         
        FrmRegEmpleado VerFormulario = new FrmRegEmpleado();
        PanelEscritorio.add(VerFormulario);
        VerFormulario.show();
        
    }//GEN-LAST:event_MenuRegEmpleadoActionPerformed

    private void MenuRegistrarConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarConsultorioActionPerformed
        
        FrmRegConsultorio VerFormulario = new FrmRegConsultorio();
        PanelEscritorio.add(VerFormulario);
        VerFormulario.show();
        
        
    }//GEN-LAST:event_MenuRegistrarConsultorioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    
       FrmContra verFormulario = new FrmContra();
       PanelEscritorio.add(verFormulario);
       verFormulario.show(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuConsultaP;
    private javax.swing.JMenuItem MenuConsultarConsultorio;
    private javax.swing.JMenuItem MenuConsultarEmpleado;
    private javax.swing.JMenuItem MenuConsultarM;
    private javax.swing.JMenu MenuConsultorio;
    private javax.swing.JMenu MenuEmpleado;
    private javax.swing.JMenu MenuMedico;
    private javax.swing.JMenu MenuPacientes;
    private javax.swing.JMenuItem MenuRegEmpleado;
    private javax.swing.JMenuItem MenuRegistraP;
    private javax.swing.JMenuItem MenuRegistrarConsultorio;
    private javax.swing.JMenuItem MenuRegistrarM;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JDesktopPane PanelEscritorio;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
